version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/vsgg
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/vsgg
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 500
      runas: ubuntu